name: kim_ne_yapti
description: "Kim Ne Yaptı? - Takım Takip Mobil Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.6.4
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  
  # Auth
  google_sign_in: ^6.2.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^13.2.5
  
  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
